image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: '@image_key'
  - _target_: EnsureChannelFirstd
    keys: '@image_key'
  - _target_: Orientationd
    axcodes: RAS
    keys: '@image_key'
  - _target_: Spacingd
    align_corners: true
    keys: '@image_key'
    mode: bilinear
    pixdim:
    - 1.0
    - 1.0
    - 1.0
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - PLACEHOLDER_INTENSITY_NORMALIZATION
  - _target_: CastToTyped
    dtype: $torch.float32
    keys: '@image_key'
